apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nv-secret
  namespace: cattle-neuvector-system
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: neuvector-init
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      engineVersion: v2
      templateFrom:
        - configMap:
            items:
            - key: userinitcfg.yaml
              templateAs: Values
            name: neuvector-init
          target: Data
  data:
  - secretKey: CTRL_PASSWORD 
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/neuvector
      metadataPolicy: None
      property: adminPass
  - secretKey: CTRL_USERNAME
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/neuvector
      metadataPolicy: None
      property: adminUser
