apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nv-ingress
  namespace: cattle-neuvector-system
spec:
  ingressClassName: nginx
  rules:
  - host: "nv.rajesh-kumar.in"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neuvector-service-webui
            port:
              number: 8443
