apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crds 
  namespace: argo
spec:
  generators:
  - list:
      elements:
        - cluster: rke2-harvester 
          app-name: neuvector
          chart: crd
          targetRevision: 2.7.9
          repoURL: 'https://neuvector.github.io/neuvector-helm/'
          namespace: cattle-neuvector-system
  template:
    metadata:
      name: '{{cluster}}-{{app-name}}-crds'
      namespace: argo
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
        name: '{{cluster}}'
      sources:
        - repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          helm:
            valueFiles:
              - '$values/applications/{{cluster}}/{{app-name}}/crds/values.yaml'
          chart: '{{chart}}'
        - repoURL: https://github.com/rajeshkio/new-lab-with-harvester.git 
          path: 'applications/{{cluster}}/{{app-name}}/crds'
          targetRevision: experiment-branch
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
