apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-routes
  namespace: argo
spec:
  generators:
  - list:
      elements:
        - cluster: rke2-harvester 
          app-name: neuvector
          namespace: cattle-neuvector-system
  template:
    metadata:
      name: '{{cluster}}-{{app-name}}-ingressroute'
      namespace: argo
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
        name: '{{cluster}}'
      source:
        repoURL: https://github.com/rajeshkio/new-lab-with-harvester.git 
        path: 'applications/{{cluster}}/{{app-name}}/ingressRoute'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
