apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets
  namespace: argo
spec:
  generators:
  - list:
      elements:
        - cluster: rke2-harvester 
          app-name: neuvector
          namespace: cattle-neuvector-system
  template:
    metadata:
      name: '{{cluster}}-{{app-name}}-externalsecret'
      namespace: argo
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
        name: '{{cluster}}'
      source:
        repoURL: https://github.com/rajeshkio/new-lab-with-harvester.git 
        path: 'applications/{{cluster}}/{{app-name}}/externalSecret'
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
