apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvClusterSecurityRule
  metadata:
    name: petra-test
    namespace: ""
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress: []
    process: []
    target:
      policymode: N/A
      selector:
        comment: ""
        criteria:
        - key: app
          op: =
          value: api
        name: petra-test
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
